version: "3.8"
services:
  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    networks:
      - backend
    volumes:
      - db:/data/db

  server1:
    build:
      context: ./favoriteBook_service
      dockerfile: Dockerfile
    ports:
      - 8081:5000
    networks:
      - backend
      - frontend
      
    depends_on:
      - mongodb
    
  server2:
    build:
      context: ./user_service
      dockerfile: Dockerfile
    ports:
      - 8082:5001
    networks:
      - backend
      - frontend
      
    depends_on:
      - mongodb

  client:
    build: 
      context: ./bookapp_dashboard
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    networks:
      - frontend
    depends_on:
      - server1
      - server2
    command: npm start
volumes: 
  db:
   
networks:
  frontend:
  backend:
   

 

